-- Security Fix: Revoke EXECUTE on SECURITY DEFINER functions
-- Run this in Supabase SQL Editor to fix the security vulnerability
-- 
-- Issue: public.rls_auto_enable() can be executed by signed-in users (authenticated role)
-- and anonymous users (anon role) via /rest/v1/rpc/rls_auto_enable
--
-- This is a security risk because SECURITY DEFINER functions run with the privileges
-- of the function owner (usually postgres), potentially allowing privilege escalation.

-- ============================================
-- Fix 1: Revoke EXECUTE on rls_auto_enable
-- ============================================
-- This function is auto-generated by Supabase and should not be callable by users

DO $$
BEGIN
  -- Check if the function exists before attempting to revoke
  IF EXISTS (
    SELECT 1 FROM pg_proc 
    WHERE proname = 'rls_auto_enable' 
    AND pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public')
  ) THEN
    -- Revoke from all roles
    REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM anon;
    REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM authenticated;
    REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM public;
    
    RAISE NOTICE 'Revoked EXECUTE on public.rls_auto_enable() from anon, authenticated, and public roles';
  ELSE
    RAISE NOTICE 'Function public.rls_auto_enable() does not exist, skipping';
  END IF;
END $$;

-- ============================================
-- Fix 2: Revoke EXECUTE on handle_new_user
-- ============================================
-- This is our trigger function that creates profiles on user signup
-- It uses SECURITY DEFINER because it needs to cross schema boundaries
-- (triggered by auth.users, inserts into public.profiles)
-- 
-- SECURITY DEFINER is REQUIRED for this trigger to work correctly.
-- We revoke direct execution but the trigger can still invoke it.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc 
    WHERE proname = 'handle_new_user' 
    AND pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public')
  ) THEN
    -- Revoke from anon and authenticated (direct API calls)
    REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon;
    REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM authenticated;
    
    -- Note: We do NOT revoke from public because the trigger mechanism needs it
    -- The trigger is secure because it only fires on INSERT to auth.users
    -- which is already protected by Supabase auth
    
    RAISE NOTICE 'Revoked EXECUTE on public.handle_new_user() from anon and authenticated roles';
  ELSE
    RAISE NOTICE 'Function public.handle_new_user() does not exist, skipping';
  END IF;
END $$;

-- ============================================
-- Fix 3: Audit all SECURITY DEFINER functions
-- ============================================
-- List all SECURITY DEFINER functions in public schema for review

SELECT 
  n.nspname as schema,
  p.proname as function_name,
  pg_get_function_identity_arguments(p.oid) as arguments,
  CASE 
    WHEN p.prosecdef THEN 'SECURITY DEFINER'
    ELSE 'SECURITY INVOKER'
  END as security_type,
  pg_catalog.pg_get_userbyid(p.proowner) as owner
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.prokind = 'f'
ORDER BY p.proname;

-- ============================================
-- Verification Queries
-- ============================================
-- Run these to verify the fixes were applied

-- Check rls_auto_enable permissions
SELECT 
  grantee,
  privilege_type
FROM information_schema.role_routine_grants
WHERE routine_name = 'rls_auto_enable'
  AND routine_schema = 'public';

-- Check handle_new_user permissions
SELECT 
  grantee,
  privilege_type
FROM information_schema.role_routine_grants
WHERE routine_name = 'handle_new_user'
  AND routine_schema = 'public';

-- ============================================
-- Expected Results
-- ============================================
-- After running this script:
-- 1. rls_auto_enable should have NO execute grants for anon, authenticated, or public
-- 2. handle_new_user should only be executable by the trigger mechanism
-- 3. The security warnings in Supabase dashboard should be resolved
--
-- Note: If you see grants to 'postgres' or 'supabase_admin', those are fine.
-- Those are administrative roles, not API-callable roles.
